name: Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
        swift: [5.6]
    runs-on: ${{ matrix.os }}
    env:
      SWIFT_VERSION: ${{ matrix.swift }}
      SWIFT_EXEC: .swiftenv/shims/swift
    steps:
    - uses: actions/checkout@v1
    - name: Install swift
      run: |
        git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
        ~/.swiftenv/bin/swiftenv install "$SWIFT_VERSION" || true
        ~/.swiftenv/bin/swiftenv rehash
    - name: Build
      run: |
        ~/$SWIFT_EXEC --version
        ~/$SWIFT_EXEC build
